/**
 * @deprecated Use {@link WORKSPACE_ENTITY_HEADER_SHELL} from workspaceEntityDetailLayout.
 */
export {
  WORKSPACE_ENTITY_HEADER_ART_CELL as SHOW_DETAIL_HERO_ART_CELL,
  WORKSPACE_ENTITY_HEADER_ART_IMAGE as SHOW_DETAIL_HERO_ART_IMAGE,
  WORKSPACE_ENTITY_HEADER_BANNER as SHOW_DETAIL_HERO_BANNER,
  WORKSPACE_ENTITY_HEADER_KPI_ROW as SHOW_DETAIL_HERO_KPI_ROW,
  WORKSPACE_ENTITY_HEADER_MAIN as SHOW_DETAIL_HERO_MAIN,
  WORKSPACE_ENTITY_METADATA_ROW as SHOW_DETAIL_HERO_METADATA,
  WORKSPACE_ENTITY_METADATA_SEP as SHOW_DETAIL_HERO_METADATA_SEP,
  WORKSPACE_ENTITY_HEADER_SHELL as SHOW_DETAIL_HERO_SHELL,
  WORKSPACE_ENTITY_HEADER_TITLE as SHOW_DETAIL_HERO_TITLE,
} from '@/app/(admin)/admin/_lib/workspaceEntityDetailLayout';
