name: Deploy Frontend (dev)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-dev
  cancel-in-progress: true

env:
  AWS_REGION: us-west-2
  S3_BUCKET: fefeave-frontend-dev
  CF_DIST_ID: ${{ vars.CF_DIST_ID }}
  ANGULAR_PROJECT: ${{ vars.ANGULAR_PROJECT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Unit tests (optional)
        run: npm test --if-present -- --watch=false

      - name: Build Angular (prod)
        run: npx ng build --configuration production

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::356892335988:role/fefeave-frontend-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload assets (long cache)
        run: |
          aws s3 cp "dist/${{ env.ANGULAR_PROJECT }}/" "s3://${{ env.S3_BUCKET }}/" \
            --recursive \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable"

      - name: Upload index.html (no-cache)
        run: |
          aws s3 cp "dist/${{ env.ANGULAR_PROJECT }}/index.html" "s3://${{ env.S3_BUCKET }}/index.html" \
            --cache-control "no-cache"

      - name: Cleanup removed files (optional)
        run: |
          aws s3 sync "dist/${{ env.ANGULAR_PROJECT }}/" "s3://${{ env.S3_BUCKET }}/" --delete

      - name: Invalidate index.html
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ env.CF_DIST_ID }}" \
            --paths "/index.html"
