name: Deploy frontend (dev)

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CF_DIST_ID: ${{ vars.CF_DIST_ID }}
  ANGULAR_PROJECT: ${{ vars.ANGULAR_PROJECT }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}

concurrency:
  group: frontend-dev
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build Angular (prod)
        working-directory: frontend
        run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Upload static assets (cache forever)
        run: |
          aws s3 sync "frontend/dist/${ANGULAR_PROJECT}/browser" "s3://${S3_BUCKET}/" \
            --exclude "index.html" \
            --delete \
            --cache-control "public, max-age=31536000, immutable"

      - name: Upload index.html (no-cache)
        run: |
          aws s3 cp "frontend/dist/${ANGULAR_PROJECT}/browser/index.html" "s3://${S3_BUCKET}/index.html" \
            --cache-control "no-cache"

      - name: Invalidate CloudFront /index.html
        run: |
          aws cloudfront create-invalidation --distribution-id "${CF_DIST_ID}" --paths "/index.html"
